apiVersion: 1

deleteDatasources:
    - name: Loki
      orgId: 1

datasources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: true
      editable: true
      version: 2
      jsonData:
          derivedFields:
              - name: traceId
                matcherRegex: '"traceId":"([0-9a-f]{32})"'
                datasourceUid: tempo
                url: '$${__value.raw}'
