// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from 'dotenv';
import path from 'node:path';
import { defineConfig } from 'prisma/config';

loadEnv({
    path: [`.env.${process.env.NODE_ENV || 'development'}`, '.env'],
    quiet: true
});

export default defineConfig({
    schema: path.join('prisma', 'admin'),
    migrations: {
        path: path.join('prisma', 'admin-migrations')
    },
    datasource: {
        url: process.env['ADMIN_DATABASE_URL']
    }
});
