export const APP_USER_ADMIN_ACTOR_ID_METADATA_KEY = 'x-shiro-actor-id';
export const APP_USER_ADMIN_ACTOR_NAME_METADATA_KEY = 'x-shiro-actor-name';
export const APP_USER_ADMIN_SCOPES_METADATA_KEY = 'x-shiro-control-plane-scopes';
export const APP_USER_ADMIN_REASON_METADATA_KEY = 'x-shiro-operation-reason';

export type AppUserAdminRpcMethod =
    | 'ListBusinessUsers'
    | 'ListBusinessRoles'
    | 'GetBusinessUser'
    | 'GetBusinessUserRoleIds'
    | 'CreateBusinessUser'
    | 'UpdateBusinessUser'
    | 'UpdateBusinessUserStatus'
    | 'SoftDeleteBusinessUser'
    | 'DeleteBusinessUser'
    | 'ResetBusinessUserPassword'
    | 'ListAdminUsers'
    | 'GetAdminUser'
    | 'CreateAdminUser'
    | 'UpdateAdminUser'
    | 'BanAdminUser'
    | 'UnbanAdminUser'
    | 'ListAdminUserSessions'
    | 'ImpersonateAdminUser'
    | 'StopImpersonatingAdminUser'
    | 'RevokeAdminUserSession'
    | 'RevokeAdminUserSessions'
    | 'RemoveAdminUser'
    | 'SetAdminUserPassword'
    | 'CheckAdminUserPermission'
    | 'GetRoleMenuIds'
    | 'AssignRoleMenus'
    | 'RemoveRoleMenuPolicy'
    | 'ListRbacRoles'
    | 'GetRbacRoleRelations'
    | 'QueryRbacRoleAssignableUsers'
    | 'QueryRbacRoleAssignableUserGroups'
    | 'QueryRbacRoleAssignableParentRoles'
    | 'QueryRbacRoleAssignablePermissions'
    | 'QueryRbacRoleEffectiveUsers'
    | 'CreateRbacRole'
    | 'UpdateRbacRole'
    | 'DeleteRbacRole'
    | 'AssignRbacRoleUsers'
    | 'AssignRbacRoleUserGroups'
    | 'AssignRbacRoleParentRoles'
    | 'AssignRbacRolePermissions'
    | 'ListRbacUserGroups'
    | 'GetRbacUserGroupRelations'
    | 'QueryRbacUserGroupMembers'
    | 'QueryRbacUserGroupRoles'
    | 'QueryRbacUserGroupMenus'
    | 'CreateRbacUserGroup'
    | 'UpdateRbacUserGroup'
    | 'DeleteRbacUserGroup'
    | 'AssignRbacUserGroupMembers'
    | 'AssignRbacUserGroupRoles'
    | 'ListRbacPermissions'
    | 'GetRbacPermissionDeclarationBoard'
    | 'SuggestRbacPermissionCode'
    | 'CreateRbacPermission'
    | 'UpdateRbacPermission'
    | 'DeleteRbacPermission'
    | 'GetRbacPermissionRelations'
    | 'QueryRbacPermissionRoles'
    | 'AssignRbacPermissionRoles'
    | 'ListRbacPermissionGroups'
    | 'CreateRbacPermissionGroup'
    | 'UpdateRbacPermissionGroup'
    | 'DeleteRbacPermissionGroup'
    | 'GetRbacPermissionGroupRelations'
    | 'AssignRbacPermissionGroupRelations'
    | 'ListRbacMenuTree'
    | 'ListRbacMenus'
    | 'GetRbacMenuDetail'
    | 'CreateRbacMenu'
    | 'UpdateRbacMenu'
    | 'DeleteRbacMenu'
    | 'GetAbacHealth'
    | 'GetAbacFields'
    | 'ListAbacFieldRegistry'
    | 'UpsertAbacField'
    | 'DeleteAbacField'
    | 'ListAbacRbacPermissionOptions'
    | 'ListAbacPolicyGroups'
    | 'UpsertAbacPolicyGroup'
    | 'DeleteAbacPolicyGroup'
    | 'ListAbacManualPolicies'
    | 'ValidateAbacManualPolicy'
    | 'UpsertAbacManualPolicy'
    | 'DeleteAbacManualPolicy'
    | 'PreviewAbacCompile'
    | 'PreviewAbacPublish'
    | 'PublishAbac'
    | 'GetAbacReleases'
    | 'RollbackAbacRelease'
    | 'TestAbacRuntime';

export type AppUserAdminAbacRpcMethod = Extract<
    AppUserAdminRpcMethod,
    | 'GetAbacHealth'
    | 'GetAbacFields'
    | 'ListAbacFieldRegistry'
    | 'UpsertAbacField'
    | 'DeleteAbacField'
    | 'ListAbacRbacPermissionOptions'
    | 'ListAbacPolicyGroups'
    | 'UpsertAbacPolicyGroup'
    | 'DeleteAbacPolicyGroup'
    | 'ListAbacManualPolicies'
    | 'ValidateAbacManualPolicy'
    | 'UpsertAbacManualPolicy'
    | 'DeleteAbacManualPolicy'
    | 'PreviewAbacCompile'
    | 'PreviewAbacPublish'
    | 'PublishAbac'
    | 'GetAbacReleases'
    | 'RollbackAbacRelease'
    | 'TestAbacRuntime'
>;

export const APP_USER_ADMIN_RPC_SCOPE_MAP: Record<AppUserAdminRpcMethod, string> = {
    ListBusinessUsers: 'app.user.read',
    ListBusinessRoles: 'app.role.read',
    GetBusinessUser: 'app.user.read',
    GetBusinessUserRoleIds: 'app.user.read',
    CreateBusinessUser: 'app.user.create',
    UpdateBusinessUser: 'app.user.update',
    UpdateBusinessUserStatus: 'app.user.status.update',
    SoftDeleteBusinessUser: 'app.user.soft-delete',
    DeleteBusinessUser: 'app.user.delete',
    ResetBusinessUserPassword: 'app.user.password.reset',
    ListAdminUsers: 'app.auth.admin-user.read',
    GetAdminUser: 'app.auth.admin-user.read',
    CreateAdminUser: 'app.auth.admin-user.create',
    UpdateAdminUser: 'app.auth.admin-user.update',
    BanAdminUser: 'app.auth.admin-user.ban',
    UnbanAdminUser: 'app.auth.admin-user.unban',
    ListAdminUserSessions: 'app.auth.admin-user.session.read',
    ImpersonateAdminUser: 'app.auth.admin-user.impersonate',
    StopImpersonatingAdminUser: 'app.auth.admin-user.impersonate.stop',
    RevokeAdminUserSession: 'app.auth.admin-user.session.revoke',
    RevokeAdminUserSessions: 'app.auth.admin-user.session.revoke',
    RemoveAdminUser: 'app.auth.admin-user.remove',
    SetAdminUserPassword: 'app.auth.admin-user.password.set',
    CheckAdminUserPermission: 'app.auth.admin-user.permission.check',
    GetRoleMenuIds: 'app.role-menu.read',
    AssignRoleMenus: 'app.role-menu.assign',
    RemoveRoleMenuPolicy: 'app.role-menu.remove',
    ListRbacRoles: 'app.rbac.role.view',
    GetRbacRoleRelations: 'app.rbac.role.view',
    QueryRbacRoleAssignableUsers: 'app.rbac.role.view',
    QueryRbacRoleAssignableUserGroups: 'app.rbac.role.view',
    QueryRbacRoleAssignableParentRoles: 'app.rbac.role.view',
    QueryRbacRoleAssignablePermissions: 'app.rbac.role.view',
    QueryRbacRoleEffectiveUsers: 'app.rbac.role.view',
    CreateRbacRole: 'app.rbac.role.create',
    UpdateRbacRole: 'app.rbac.role.update',
    DeleteRbacRole: 'app.rbac.role.delete',
    AssignRbacRoleUsers: 'app.rbac.role.assign-user',
    AssignRbacRoleUserGroups: 'app.rbac.role.assign-user-group',
    AssignRbacRoleParentRoles: 'app.rbac.role.assign-parent-role',
    AssignRbacRolePermissions: 'app.rbac.role.assign-permission',
    ListRbacUserGroups: 'app.rbac.user-group.view',
    GetRbacUserGroupRelations: 'app.rbac.user-group.view',
    QueryRbacUserGroupMembers: 'app.rbac.user-group.view',
    QueryRbacUserGroupRoles: 'app.rbac.user-group.view',
    QueryRbacUserGroupMenus: 'app.rbac.user-group.view',
    CreateRbacUserGroup: 'app.rbac.user-group.create',
    UpdateRbacUserGroup: 'app.rbac.user-group.update',
    DeleteRbacUserGroup: 'app.rbac.user-group.delete',
    AssignRbacUserGroupMembers: 'app.rbac.user-group.assign-member',
    AssignRbacUserGroupRoles: 'app.rbac.user-group.assign-role',
    ListRbacPermissions: 'app.rbac.permission.view',
    GetRbacPermissionDeclarationBoard: 'app.rbac.permission.view',
    SuggestRbacPermissionCode: 'app.rbac.permission.create',
    CreateRbacPermission: 'app.rbac.permission.create',
    UpdateRbacPermission: 'app.rbac.permission.update',
    DeleteRbacPermission: 'app.rbac.permission.delete',
    GetRbacPermissionRelations: 'app.rbac.permission.view',
    QueryRbacPermissionRoles: 'app.rbac.permission.view',
    AssignRbacPermissionRoles: 'app.rbac.permission.assign-role',
    ListRbacPermissionGroups: 'app.rbac.permission-group.view',
    CreateRbacPermissionGroup: 'app.rbac.permission-group.create',
    UpdateRbacPermissionGroup: 'app.rbac.permission-group.update',
    DeleteRbacPermissionGroup: 'app.rbac.permission-group.delete',
    GetRbacPermissionGroupRelations: 'app.rbac.permission-group.view',
    AssignRbacPermissionGroupRelations: 'app.rbac.permission-group.assign',
    ListRbacMenuTree: 'app.rbac.menu.view',
    ListRbacMenus: 'app.rbac.menu.view',
    GetRbacMenuDetail: 'app.rbac.menu.view',
    CreateRbacMenu: 'app.rbac.menu.create',
    UpdateRbacMenu: 'app.rbac.menu.update',
    DeleteRbacMenu: 'app.rbac.menu.delete',
    GetAbacHealth: 'app.abac.page',
    GetAbacFields: 'app.abac.page',
    ListAbacFieldRegistry: 'app.abac.field.read',
    UpsertAbacField: 'app.abac.field.write',
    DeleteAbacField: 'app.abac.field.write',
    ListAbacRbacPermissionOptions: 'app.abac.policy-group.read',
    ListAbacPolicyGroups: 'app.abac.policy-group.read',
    UpsertAbacPolicyGroup: 'app.abac.policy-group.write',
    DeleteAbacPolicyGroup: 'app.abac.policy-group.write',
    ListAbacManualPolicies: 'app.abac.manual-policy.read',
    ValidateAbacManualPolicy: 'app.abac.manual-policy.write',
    UpsertAbacManualPolicy: 'app.abac.manual-policy.write',
    DeleteAbacManualPolicy: 'app.abac.manual-policy.write',
    PreviewAbacCompile: 'app.abac.preview',
    PreviewAbacPublish: 'app.abac.publish',
    PublishAbac: 'app.abac.publish',
    GetAbacReleases: 'app.abac.publish',
    RollbackAbacRelease: 'app.abac.publish',
    TestAbacRuntime: 'app.abac.runtime-test'
};
