export const SPICEDB_MODULE_OPTIONS = 'SPICEDB_MODULE_OPTIONS';
export const SPICEDB_PERMISSION_METADATA_KEY = 'SPICEDB_PERMISSION_METADATA_KEY';
export const SPICEDB_RESOLVERS_METADATA_KEY = 'SPICEDB_RESOLVERS_METADATA_KEY';
