apiVersion: 1

deleteDatasources:
    - name: Loki
      orgId: 1

datasources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: https://loki:3100
      isDefault: true
      editable: true
      version: 2
      jsonData:
          tlsAuth: true
          tlsAuthWithCACert: true
          serverName: loki
          tlsAuthWithCACertPath: /etc/grafana/certs/ca.crt
          tlsClientCertPath: /etc/grafana/certs/client.crt
          tlsClientKeyPath: /etc/grafana/certs/client.key
          derivedFields:
              - name: traceId
                matcherRegex: '"traceId":"([0-9a-f]{32})"'
                datasourceUid: tempo
                url: '$${__value.raw}'
